// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBlwgtryqosnFcLqmXlKiL55tjOQWQc0Y',
    appId: '1:270866059115:web:8ac1f6b97d0cfb5147c62e',
    messagingSenderId: '270866059115',
    projectId: 'gymbandungcenter',
    authDomain: 'gymbandungcenter.firebaseapp.com',
    storageBucket: 'gymbandungcenter.firebasestorage.app',
    measurementId: 'G-K5314FMWNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7zBYaqGg42m6Rtgr56FYHvdmJYcN6RA0',
    appId: '1:270866059115:android:1107c920dee00fd247c62e',
    messagingSenderId: '270866059115',
    projectId: 'gymbandungcenter',
    storageBucket: 'gymbandungcenter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArgVGLbaR5wKBlKANenvKVaQVWQKFfapE',
    appId: '1:270866059115:ios:0832bde175bfde9347c62e',
    messagingSenderId: '270866059115',
    projectId: 'gymbandungcenter',
    storageBucket: 'gymbandungcenter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
